### ISSUE TITLE
Make pthread key creation thread safe

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/pthread-os2#2]
There is a pthread key destructor implementation in c485249 (by @komh) but it it's not thread-safe. I.e. if two threads will attempt to create two keys at the same time, the behavior is undefined (data corruption most likely).

Needed for bitwiseworks/qtwebengine-chromium-os2#3 as Chromium may use it from multiple threads (e.g. at startup time, see its `thread_local_storage.cc`).

**Comment by dmik** [comment]
Note that I basically redid key destructor processing in the above commit — to provide thread safety. Now it is organized not as a linked list but simply as an array. Given that our PTHREAD_KEYS_MAX is 64 for now, it only gives additional 256 bytes (64 * 4) **per process**. That's nothing and much easier to maintain than the linked list (and doesn't create heap fragmentation).

Also note that this commit fixes heap memory leaks that would occur each time a thread started with `pthread_create` would use `pthread_[get|set]specific` and then terminate (normally). This would lead to a loss of 256 bytes per each such thread. In case if an application creates (and ends) lots of threads, this could expose a significant memory leak (imagine the application starts/stops a 1000 threads over its life time — it's almost 256KB of memory).

Note that some memory leaks are still there. E.g. if `pthread_[get|set]specific` is used in a thread started with `_beginthread` or `DosCreateThread`. Also some global resources are not explicitly freed upon process termination. This is covered in different tickets — #1 and #4, respectively. Not  critical, so both are postponed.

**Comment by komh** [comment]
Then, how about https://github.com/bitwiseworks/gcc-os2/blob/16a351da1e6ad6c4b9112f2f43fb25870a134807/libgcc/gthr-os2.c#L268 ? I think, it's also not thread-safe. It should be fixed as well unless gcc considers thread-safety for __gthread_os2_create().

**Comment by dmik** [comment]
@komh thanks for noticing it! I've created a separate ticket for that. We need to implement thread safety on our own, C++ doesn't ensure it.
